#!/python
import pprint
import requests
mac_url = 'http://macvendors.co/api/%s'
mac_address = input('Please enter a MAC address:n format of 00:00:00:00:00 : ')
r = requests.get(mac_url % mac_address)
pprint.pprint(r.json())
